title: "视频下载"
description: "使用 yt-dlp 从各大视频网站下载视频"
icon: ":carbon:download"

inputs_def:
  - handle: url
    description: "视频URL"
    json_schema:
      type: string
    nullable: false
  
  - handle: format
    description: "下载格式 (best/bestvideo+bestaudio/mp4/webm等)"
    json_schema:
      type: string
    value: "best"
    nullable: true
  
  - handle: output_dir
    description: "输出目录"
    json_schema:
      type: string
      ui:widget: dir
    value: "/oomol-driver/oomol-storage/downloads"
    nullable: true
  
  - handle: filename_template
    description: "文件名模板 (%(title)s.%(ext)s)"
    json_schema:
      type: string
    value: "%(title)s.%(ext)s"
    nullable: true
  
  - handle: quality
    description: "视频质量 (best/1080p/720p/480p/360p)"
    json_schema:
      type: string
    value: "best"
    nullable: true
  
  - handle: audio_only
    description: "仅下载音频"
    json_schema:
      type: boolean
    value: false
    nullable: true
  
  - handle: subtitle_langs
    description: "字幕语言代码 (如 zh-CN,en)"
    json_schema:
      type: string
    nullable: true
  
  - handle: proxy
    description: "代理地址 (如 http://127.0.0.1:1080)"
    json_schema:
      type: string
    nullable: true

outputs_def:
  - handle: video_path
    description: "下载的视频文件路径"
    json_schema:
      type: string
  
  - handle: info
    description: "视频信息"
    json_schema:
      type: object
      properties:
        title:
          type: string
        duration:
          type: number
        uploader:
          type: string
        view_count:
          type: number
        upload_date:
          type: string
        webpage_url:
          type: string
        thumbnail:
          type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false