title: "%video-download3%"
description: "%download-videos-from-major-video-websites-using-yt-dlp2%"
icon: ":carbon:download:"

inputs_def:
  - handle: url
    description: "%video-url%"
    json_schema:
      type: string
    nullable: false

  - handle: output_dir
    description: "%output-directory%"
    json_schema:
      type: string
      ui:widget: dir
    nullable: false

  - handle: format
    description: "%download-format2%"
    json_schema:
      type: string
      enum:
        - best
        - bestvideo+bestaudio
        - mp4
        - webm
        - mkv
        - flv
    value: best
    nullable: true

  - handle: filename_template
    description: "%filename-template%"
    json_schema:
      type: string
    value:
    nullable: true

  - handle: quality
    description: "%video-quality%"
    json_schema:
      type: string
      enum:
        - best
        - 4K
        - 2160p
        - 1440p
        - 1080p
        - 720p
        - 480p
        - 360p
        - 240p
    value: best
    nullable: true

  - handle: audio_only
    description: "%audio-only%"
    json_schema:
      type: boolean
    value: false
    nullable: true

  - handle: subtitle_langs
    description: "%subtitle-language-codes-e-g-zh-cn-en%"
    json_schema:
      type: string
      enum:
        - "en"
        - "zh-CN"
        - "ja"
        - "fr"
    value:
    nullable: true

  - handle: proxy
    description: "%proxy-address-e-g-http-127-0-0-1-10802%"
    json_schema:
      type: string
    value:
    nullable: true

  - handle: hdr
    description: "%download-hdr-video-if-available2%"
    json_schema:
      type: boolean
    value: true
    nullable: true

  - handle: high_fps
    description: "%download-high-frame-rate-video-50fps-if-available2%"
    json_schema:
      type: boolean
    value: true
    nullable: true

  - handle: codec_preference
    description: "%preferred-video-codec-leave-empty-for-best-quality2%"
    json_schema:
      type: string
      enum:
        - h264
        - h265
        - av1
        - vp9
    value:
    nullable: true

  - handle: bitrate_limit
    description: "%maximum-bitrate-limit-e-g-5000k-10m2%"
    json_schema:
      type: string
    value:
    nullable: true

  - handle: cookies_file
    description: "%cookie-file-path-for-authentication2%"
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        filters:
          - name: Cookie Files
            extensions:
              - txt
              - cookies
          - name: All Files
            extensions:
              - "*"
    value:
    nullable: true

outputs_def:
  - handle: video_path
    description: "Downloaded video file path"
    json_schema:
      type: string

  - handle: info
    description: "Video information"
    json_schema:
      type: object
      properties:
        title:
          type: string
        duration:
          type: number
        uploader:
          type: string
        view_count:
          type: number
        upload_date:
          type: string
        webpage_url:
          type: string
        thumbnail:
          type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
