title: "Video Download"
description: "Download videos from major video websites using yt-dlp"
icon: ":carbon:download:"

inputs_def:
  - handle: url
    description: "Video URL"
    json_schema:
      type: string
    nullable: false

  - handle: output_dir
    description: "Output directory"
    json_schema:
      type: string
      ui:widget: dir
    nullable: false

  - handle: format
    description: "Download format"
    json_schema:
      type: string
      enum:
        - best
        - bestvideo+bestaudio
        - mp4
        - webm
        - mkv
        - flv
    value: best
    nullable: true

  - handle: filename_template
    description: "Filename template"
    json_schema:
      type: string
    value:
    nullable: true

  - handle: quality
    description: "Video quality"
    json_schema:
      type: string
      enum:
        - best
        - 4K
        - 2160p
        - 1440p
        - 1080p
        - 720p
        - 480p
        - 360p
        - 240p
    value: best
    nullable: true

  - handle: audio_only
    description: "Audio only"
    json_schema:
      type: boolean
    value: false
    nullable: true

  - handle: subtitle_langs
    description: "Subtitle language codes (e.g. zh-CN,en)"
    json_schema:
      type: string
      enum:
        - "en"
        - "zh-CN"
        - "ja"
        - "fr"
    value:
    nullable: true

  - handle: proxy
    description: "Proxy address (e.g. http://127.0.0.1:1080)"
    json_schema:
      type: string
    value:
    nullable: true

  - handle: hdr
    description: "Download HDR video if available"
    json_schema:
      type: boolean
    value: false
    nullable: true

  - handle: high_fps
    description: "Download high frame rate video (>=50fps) if available"
    json_schema:
      type: boolean
    value: false
    nullable: true

  - handle: codec_preference
    description: "Preferred video codec"
    json_schema:
      type: string
      enum:
        - h264
        - h265
        - av1
        - vp9
    value: h264
    nullable: true

  - handle: bitrate_limit
    description: "Maximum bitrate limit (e.g. 5000k, 10m)"
    json_schema:
      type: string
    value:
    nullable: true

outputs_def:
  - handle: video_path
    description: "Downloaded video file path"
    json_schema:
      type: string

  - handle: info
    description: "Video information"
    json_schema:
      type: object
      properties:
        title:
          type: string
        duration:
          type: number
        uploader:
          type: string
        view_count:
          type: number
        upload_date:
          type: string
        webpage_url:
          type: string
        thumbnail:
          type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
